version: '2'

services:
    web:
        build: .
        ports:
            - '10008:80'
        stdin_open: true
        tty: true
        volumes:
            - ./source/upload:/var/www/html/upload
