version: '2'

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ctf
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - '80:80'
    volumes:
      - ./source:/var/www/html
      - ./logs:/var/log/apache2
    stdin_open: true
